version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    target_branch: master
    update_schedule: weekly
    default_reviewers:
      - stuft2
    automerged_updates:
      - match:
          update_type: "semver:patch"
